version: '3.3'

services:
  publikator:
    image: 192.168.1.53:5000/publicator:8.3.20.2180
    ports:
      - 999:80
      - 3334:3333
    volumes:
      - "./volumes/config:/opt/app/winow/config"
      # - "./volumes/autumn-properties.json:/opt/app/winow/autumn-properties.json"
    