version: '3.3'

services:
  publikator:
    image: 192.168.1.53:5000/publicator:8.3.20.2180
    ports:
      - 998:80
      - 3333:3333
    volumes:
     - ./volumes/config.json:/opt/app/winow/config/config.json
     - ./volumes/autumn-properties.json:/opt/app/winow/autumn-properties.json